apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: encodec-api
  namespace: encodec-api
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - encodec.wavey.ai
      secretName: encodec-wavey-ai-tls
  rules:
    - host: encodec.wavey.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: encodec-api-ingress
                port:
                  number: 8443
