apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - serviceaccount.yaml
  - ingress-configmap.yaml
  - worker-configmap.yaml
  - ingress-deployment.yaml
  - worker-deployment.yaml
  - services.yaml
  - ingress.yaml
